spring:
  application:
    name: petclinic

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petclinic
    username: dev33
    password: ezflow_010

  jpa:
    open-in-view: false
    show-sql: false

  sql:
    init:
      mode: never


  thymeleaf:
    mode: HTML

  messages:
    basename: messages/messages
    encoding: UTF-8
    cache-duration: 5m

  management:
    endpoints:
      web:
        exposure:
          include: "*"

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 12h

logging:
  level:
    org.springframework: INFO
    # org.springframework.web: DEBUG
    # org.springframework.context.annotation: TRACE
